### ISSUE TITLE
Parallel projects

### ISSUE THREAD

**Issue by burner1024** [dbostr/weidu-syntax#1]
Hi. Just want to make you aware of some parallel projects: [1](https://github.com/WeiDUorg/weidu-vscode-syntax), [2](https://github.com/BGforgeNet/vscode-bgforge-mls).

**Comment by dbostr** [comment]
Excellent. This is mostly a by-product of what I ran into myself.

**Comment by burner1024** [comment]
We're conspiring to join forces, so if by chance you want to chip in, that'll be most welcome.
